apiVersion: v1
kind: Secret
metadata:
  name: mmrelay-credentials-json
  namespace: {{NAMESPACE}}
  labels:
    app: mmrelay
type: Opaque
stringData:
  # This secret stores the credentials.json file generated by 'mmrelay auth login'
  #
  # To create this secret:
  # 1. Run 'mmrelay auth login' locally to generate credentials.json
  # 2. Create the secret from the file:
  #    kubectl create secret generic mmrelay-credentials-json \
  #      --from-file=credentials.json=<path-to-credentials.json> \
  #      --namespace={{NAMESPACE}}
  #
  # Note: The default location is $HOME/.mmrelay/credentials.json. If you used a custom
  # --data-dir when running mmrelay auth login, use that directory instead.
  #
  # Alternatively, paste the JSON content below:
  credentials.json: |
    {
      "homeserver": "https://matrix.example.org",
      "user_id": "@bot:example.org",
      "device_id": "DEVICEID",
      "access_token": "your_access_token_here"
    }
