name: Build Android APK

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # The setup-android action will automatically use the ANDROID_HOME environment variable.
      # It will also add the necessary tools to the PATH.
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Android App
        working-directory: android
        run: ./gradlew build
        env:
          # The setup-android action sets ANDROID_HOME, but we can be explicit
          # if needed. This is good practice.
          ANDROID_HOME: ${{ env.ANDROID_HOME }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: mmrelay-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
